# Generated by Django 6.0.6 on 2026-07-03 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Manutenção', 'Manutenção'), ('Desligado', 'Desligado'), ('Reserva', 'Reserva')], default='Ativo', max_length=20)),
                ('armazenamento', models.CharField(blank=True, max_length=100)),
                ('placa_video', models.CharField(blank=True, max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('sistema', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('processador', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['sala', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='plantas/')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('acao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ativos.computador')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
